// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_Ly-eCx3f-CNRoiPsRiExvvh8ekU5bo',
    appId: '1:375400582595:web:16e1a6715368d29ba3c176',
    messagingSenderId: '375400582595',
    projectId: 'love-sync-675db',
    authDomain: 'love-sync-675db.firebaseapp.com',
    storageBucket: 'love-sync-675db.firebasestorage.app',
    measurementId: 'G-YHGNM62LNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GENp4vEKHfds1P9LUddTOMw4q_2fH3E',
    appId: '1:375400582595:android:2974f5e3c2210988a3c176',
    messagingSenderId: '375400582595',
    projectId: 'love-sync-675db',
    storageBucket: 'love-sync-675db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sn4J8nhReoshM4pWGOv-1F0jwouMTfw',
    appId: '1:375400582595:ios:6ba7448859299f77a3c176',
    messagingSenderId: '375400582595',
    projectId: 'love-sync-675db',
    storageBucket: 'love-sync-675db.firebasestorage.app',
    iosBundleId: 'com.example.lovesyncMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0sn4J8nhReoshM4pWGOv-1F0jwouMTfw',
    appId: '1:375400582595:ios:6ba7448859299f77a3c176',
    messagingSenderId: '375400582595',
    projectId: 'love-sync-675db',
    storageBucket: 'love-sync-675db.firebasestorage.app',
    iosBundleId: 'com.example.lovesyncMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt_Ly-eCx3f-CNRoiPsRiExvvh8ekU5bo',
    appId: '1:375400582595:web:ff6b0eaab29bc31ea3c176',
    messagingSenderId: '375400582595',
    projectId: 'love-sync-675db',
    authDomain: 'love-sync-675db.firebaseapp.com',
    storageBucket: 'love-sync-675db.firebasestorage.app',
    measurementId: 'G-VNE1KRBKD3',
  );
}
